### PR TITLE
Changes needed to get things running

### PR DESCRIPTION
**Pull request by alexkalderimis**
This includes:

- asdf integration
- Use of dotenv to manage DB passwords
- Updated schema file

And importantly, resolution of port conflicts.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (if relevant)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix
- [ ] New feature
- [x] A documentation update
- [ ] Refactoring

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**If this is a UI change / fix, please also add a screenshot**

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I added the relevant people as reviewers to my PR

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @alexkalderimis, I'll review the changes right away.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
It looks like we still have some problems. <br>To make it easier for new engineers to get the system up and running, is there a way you can make the readme file a bit more friendly?

**Review by vanessa-cooper — APPROVED** [review]
Awesome! Thanks so much for taking the time to make the setup experience a little smoother. Hopefully new engineers will now have a much easier start 🌟.
Now, all that’s left is to merge this PR, and the next item will be ready for you in Slack.

**Comment by alexkalderimis** [comment]
@vanessa-cooper - how can I merge this PR?

**Comment by vanessa-cooper** [comment]
You need to accept the invite to join the repo and then you'll be able to
merge

**Comment by alexkalderimis** [comment]
Thanks @vanessa-cooper - I think that invitation has expired. When you have time, perhaps you could send another one?

**Pull request merged**
